#!/bin/bash

if [ -z "$1" ]
	then
    echo "usage: lever <program_name>"
    exit 1
fi

echo Compiling Lever into intermediate code... 
java -cp "../translator:/usr/local/lib/antlr-4.5-complete.jar" Leverc ../leverSamples/$1

echo Compiling and JARing API...
javac -cp ".:../lib/*" -d ../translator/LeverAPIPackageSourceCode/  ../translator/LeverAPIPackageSourceCode/*.java
jar cvf ../lib/LeverAPI-package.jar -C ../translator/LeverAPIPackageSourceCode  LeverAPIPackage

progName=${1//.lever/.java} #get java filename out of lever filename
echo Compiling program...
javac -cp ".:../lib/*" $progName

echo Removing intermediate files...
rm $progName
